init:
- cmd: git config --global core.autocrlf true
environment:
  NUGET_PUSH_APIKEY:
    secure: /BBmYv/HUU0lnVk7iypx0Nq5yeoD8N/LGxGA4xrUPYuqbeMsW0XuUiMSaM/GMwB3
  NUGET_PUSH_FEED:
    secure: bDDMNs4Db9yruHKBN9AHLkredI7oRY2j2hhqQpYp72iRCPnbYx6hJEh5ouQvFLxC
build_script:
- cmd: condo.cmd --coverage --secure push
test: off
deploy: off